name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grant write permissions to push tags

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Tag
        id: create_tag
        run: |
          VERSION=$(find releases -mindepth 1 -maxdepth 1 -type d -name 'v*' | sort | tail -n 1 | xargs basename)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $VERSION
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/${{ env.VERSION }}/*.jpg
            releases/${{ env.VERSION }}/*.png
            releases/${{ env.VERSION }}/*.jpeg
          generate_release_notes: true
          tag_name: ${{ env.VERSION }}
          prerelease: false
          draft: false  # Ensure release is marked as the latest
